export const environment = {
    production: false,
    Development: false,
    AppId:"VALICV2PIMP",
    DefaultUserId: "LMWFSVC",
    CreateWorkContext: "VSYS1389",
    GetProcessFlag: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/GetProcessFlag",
    FindSource: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/FindSource",
    UpdateObjectField: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/UpdateObjectField",
    UpdateCaseStatus: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/UpdateObjectStatus",
    UpdateBatchUserId:"https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/UpdateBatchUserId",
    UpdateBatch4ApprovedUser:"https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/UpdateBatch4ApprovedUser",
    UpdateBatch4DeniedUser:"https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/UpdateBatch4DeniedUser",
    GetProcBatchGridAPI: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/GetProcBatchGrid",
    GetLoanData: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/GetLoanData",
    GetBatchInfo: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/GetBatchInfo",
    UpdateAccessTime: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/UpdateAccessTime",
    DeleteOldPLP:         "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/DeleteOldPLPs",
    InsertPLP:            "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/InsertPLPs",
    UpdateRepay:          "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/UpdateRepay",
    GetRepayInfoAPI:      "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/GetRepayInfo",
    GetBatchPLPs:         "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/GetBatchPLPs",
    GetObjectData:        "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/GetObjectData",
    UpdateAWDObject4PLP:  "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/UpdateAWDObject4PLP",
    CreateWork:           "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/CreateWork",
    CreateRelationship: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/CreateRelationship",
    UnlockInstance: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/UnlockInstance",
    LockInstance: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/LockInstance",
    GetRepayPLP: "https://twsaaswise01.r1-core.r1.aig.net:8083/ValicBatchBalanceServices/api/bbapi/GetRepayPLP",
    ImageViewerAPI: "https://twsaaswise01.r1-core.r1.aig.net:448/AIG_SS_ImageViewer/?appType=DEF&DocumentId",
    RestService: "https://twsaaswise01.r1-core.r1.aig.net/Aig.WC.ServicesV2/RestServices/"                  
};
